/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.85
 * Generated at: 2023-05-08 03:32:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import comm.octest.beans.ChatRoom;
import comm.octest.dao.user.UserDAOImp;
import java.lang.reflect.Array;
import java.util.ArrayList;
import comm.octest.beans.Message;
import java.util.ArrayList;
import java.util.List;
import comm.octest.beans.Flyweight;
import comm.octest.beans.Message;
import comm.octest.beans.QuoteManager;

public final class chat_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/ressources/css/chat.css", Long.valueOf(1682901817368L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1678212913362L));
    _jspx_dependants.put("/WEB-INF/taglibs.jsp", Long.valueOf(1678214133056L));
    _jspx_dependants.put("/WEB-INF/navBar.jsp", Long.valueOf(1683340426708L));
    _jspx_dependants.put("jar:file:/C:/Users/Simofatt/workspace3/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/test/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153377882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("comm.octest.beans.QuoteManager");
    _jspx_imports_classes.add("java.lang.reflect.Array");
    _jspx_imports_classes.add("comm.octest.dao.user.UserDAOImp");
    _jspx_imports_classes.add("comm.octest.beans.Message");
    _jspx_imports_classes.add("comm.octest.beans.Flyweight");
    _jspx_imports_classes.add("comm.octest.beans.ChatRoom");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <title>Insert title here</title>\r\n");
      out.write("         <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\" crossorigin=\"anonymous\">\r\n");
      out.write("        \r\n");
      out.write("            ");

                    

                                        
                                         
                                                    String email =  (String) session.getAttribute("email");
                                                    String withClientId = (String) request.getParameter("withClientId");
                                              
                                                    
                                                    UserDAOImp user = new UserDAOImp();
                                                    
                                                      ArrayList<Message> my_messages = new ArrayList<Message>();
                                                      my_messages = (ArrayList<Message>) request.getAttribute("my_messages") ; 
                                                      String  withClientName = (String) request.getAttribute("withClientName") ;
                                                      int idUser =  user.getId(withClientId) ; 
                                                     
                                             
                                                      
                                                      try {
                                                          user.removeMsg(withClientId,email);
                                                      } catch (Exception e) {

                                                      }
                    
      out.write("\r\n");
      out.write("           <style>");
      out.write("@charset \"UTF-8\";\r\n");
      out.write("    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap');\r\n");
      out.write("            *{\r\n");
      out.write("                margin: 0;\r\n");
      out.write("                padding: 0;\r\n");
      out.write("                box-sizing: border-box;\r\n");
      out.write("                text-decoration: none;\r\n");
      out.write("                font-family: 'Poppins', sans-serif;\r\n");
      out.write("            }\r\n");
      out.write("            body{\r\n");
      out.write("                background: url(\"backgroundImage\");\r\n");
      out.write("            }\r\n");
      out.write("            #fileInput{\r\n");
      out.write("                display: none;\r\n");
      out.write("            }\r\n");
      out.write("            .container{\r\n");
      out.write("                display: flex;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("                justify-content: center;\r\n");
      out.write("                min-height: 100vh;\r\n");
      out.write("                padding: 0 10px;\r\n");
      out.write("            }\r\n");
      out.write("            .wrapper{\r\n");
      out.write("                background: #fff;\r\n");
      out.write("                max-width: 450px;\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                border-radius: 16px;\r\n");
      out.write("                box-shadow: 0 0 128px 0 rgba(0,0,0,0.1),\r\n");
      out.write("                0 32px 64px -48px rgba(0,0,0,0.5);\r\n");
      out.write("                position : relative ; \r\n");
      out.write("                left : 500px;\r\n");
      out.write("                top : 10px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            /* style for profile dropdown */\r\n");
      out.write("        .dropdown-menu-right {\r\n");
      out.write("            right: 0;\r\n");
      out.write("            left: auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar {\r\n");
      out.write("            background-color: #333;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar-brand {\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-link {\r\n");
      out.write("            color: white;\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-link:hover {\r\n");
      out.write("            color: yellow;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar-nav {\r\n");
      out.write("            margin-left: auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar-nav>li {\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .resize-none {\r\n");
      out.write("            resize: none;\r\n");
      out.write("        }\r\n");
      out.write("         \r\n");
      out.write("\r\n");
      out.write("            /* Chat Area CSS Start */\r\n");
      out.write("            .chat-area header{\r\n");
      out.write("                display: flex;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("                padding: 18px 30px;\r\n");
      out.write("            }\r\n");
      out.write("            .chat-area header .back-icon{\r\n");
      out.write("                color: #333;\r\n");
      out.write("                font-size: 18px;\r\n");
      out.write("            }\r\n");
      out.write("            .chat-area header img{\r\n");
      out.write("                height: 45px;\r\n");
      out.write("                width: 45px;\r\n");
      out.write("                margin: 0 15px;\r\n");
      out.write("            }\r\n");
      out.write("            .chat-area header .details span{\r\n");
      out.write("                font-size: 17px;\r\n");
      out.write("                font-weight: 500;\r\n");
      out.write("            }\r\n");
      out.write("            .chat-box{\r\n");
      out.write("                position: relative;\r\n");
      out.write("                min-height: 500px;\r\n");
      out.write("                max-height: 500px;\r\n");
      out.write("                overflow-y: auto;\r\n");
      out.write("                padding: 10px 30px 20px 30px;\r\n");
      out.write("                background: #f7f7f7;\r\n");
      out.write("                box-shadow: inset 0 32px 32px -32px rgb(0 0 0 / 5%),\r\n");
      out.write("                inset 0 -32px 32px -32px rgb(0 0 0 / 5%);\r\n");
      out.write("            }\r\n");
      out.write("            .chat-box .text{\r\n");
      out.write("                position: absolute;\r\n");
      out.write("                top: 45%;\r\n");
      out.write("                left: 50%;\r\n");
      out.write("                width: calc(100% - 50px);\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                transform: translate(-50%, -50%);\r\n");
      out.write("            }\r\n");
      out.write("            .chat-box .chat{\r\n");
      out.write("                margin: 15px 0;\r\n");
      out.write("            }\r\n");
      out.write("            .chat-box .chat p{\r\n");
      out.write("                word-wrap: break-word;\r\n");
      out.write("                padding: 8px 16px;\r\n");
      out.write("                box-shadow: 0 0 32px rgb(0 0 0 / 8%),\r\n");
      out.write("                0rem 16px 16px -16px rgb(0 0 0 / 10%);\r\n");
      out.write("            }\r\n");
      out.write("            .chat-box .outgoing{\r\n");
      out.write("                display: flex;\r\n");
      out.write("            }\r\n");
      out.write("            .chat-box .outgoing .details{\r\n");
      out.write("                margin-left: auto;\r\n");
      out.write("                max-width: calc(100% - 130px);\r\n");
      out.write("            }\r\n");
      out.write("            .outgoing .details p{\r\n");
      out.write("                background: #333;\r\n");
      out.write("                color: #fff;\r\n");
      out.write("                border-radius: 18px 18px 0 18px;\r\n");
      out.write("            }\r\n");
      out.write("            .chat-box .incoming{\r\n");
      out.write("                display: flex;\r\n");
      out.write("                align-items: flex-end;\r\n");
      out.write("            }\r\n");
      out.write("            .chat-box .incoming img{\r\n");
      out.write("                height: 35px;\r\n");
      out.write("                width: 35px;\r\n");
      out.write("            }\r\n");
      out.write("            .chat-box .incoming .details{\r\n");
      out.write("                margin-right: auto;\r\n");
      out.write("                margin-left: 10px;\r\n");
      out.write("                max-width: calc(100% - 130px);\r\n");
      out.write("            }\r\n");
      out.write("            .incoming .details p{\r\n");
      out.write("                background: #fff;\r\n");
      out.write("                color: #333;\r\n");
      out.write("                border-radius: 18px 18px 18px 0;\r\n");
      out.write("            }\r\n");
      out.write("            .typing-area{\r\n");
      out.write("                padding: 18px 30px;\r\n");
      out.write("                display: flex;\r\n");
      out.write("                justify-content: space-between;\r\n");
      out.write("            }\r\n");
      out.write("            .typing-area input{\r\n");
      out.write("                height: 45px;\r\n");
      out.write("                width: calc(100% - 58px);\r\n");
      out.write("                font-size: 16px;\r\n");
      out.write("                padding: 0 13px;\r\n");
      out.write("                border: 1px solid #e6e6e6;\r\n");
      out.write("                outline: none;\r\n");
      out.write("                border-radius: 5px 0 0 5px;\r\n");
      out.write("            }\r\n");
      out.write("            .typing-area button{\r\n");
      out.write("                color: #fff;\r\n");
      out.write("                width: 55px;\r\n");
      out.write("                border: none;\r\n");
      out.write("                outline: none;\r\n");
      out.write("                background: #333;\r\n");
      out.write("                font-size: 19px;\r\n");
      out.write("                cursor: pointer;\r\n");
      out.write("                opacity: 0.7;\r\n");
      out.write("                border-radius: 0 5px 5px 0;\r\n");
      out.write("                transition: all 0.3s ease;\r\n");
      out.write("            }\r\n");
      out.write("            .typing-area button.active{\r\n");
      out.write("                opacity: 1;\r\n");
      out.write("                pointer-events: auto;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            /* Responive media query */\r\n");
      out.write("            @media screen and (max-width: 450px) {\r\n");
      out.write("                .form, .users{\r\n");
      out.write("                    padding: 20px;\r\n");
      out.write("                }\r\n");
      out.write("                .form header{\r\n");
      out.write("                    text-align: center;\r\n");
      out.write("                }\r\n");
      out.write("                .form form .name-details{\r\n");
      out.write("                    flex-direction: column;\r\n");
      out.write("                }\r\n");
      out.write("                .form .name-details .field:first-child{\r\n");
      out.write("                    margin-right: 0px;\r\n");
      out.write("                }\r\n");
      out.write("                .form .name-details .field:last-child{\r\n");
      out.write("                    margin-left: 0px;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .users header img{\r\n");
      out.write("                    height: 45px;\r\n");
      out.write("                    width: 45px;\r\n");
      out.write("                }\r\n");
      out.write("                .users header .logout{\r\n");
      out.write("                    padding: 6px 10px;\r\n");
      out.write("                    font-size: 16px;\r\n");
      out.write("                }\r\n");
      out.write("                :is(.users, .users-list) .content .details{\r\n");
      out.write("                    margin-left: 15px;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .users-list a{\r\n");
      out.write("                    padding-right: 10px;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .chat-area header{\r\n");
      out.write("                    padding: 15px 20px;\r\n");
      out.write("                }\r\n");
      out.write("                .chat-box{\r\n");
      out.write("                    min-height: 400px;\r\n");
      out.write("                    padding: 10px 15px 15px 20px;\r\n");
      out.write("                }\r\n");
      out.write("                .chat-box .chat p{\r\n");
      out.write("                    font-size: 15px;\r\n");
      out.write("                }\r\n");
      out.write("                .chat-box .outogoing .details{\r\n");
      out.write("                    max-width: 230px;\r\n");
      out.write("                }\r\n");
      out.write("                .chat-box .incoming .details{\r\n");
      out.write("                    max-width: 265px;\r\n");
      out.write("                }\r\n");
      out.write("                .incoming .details img{\r\n");
      out.write("                    height: 30px;\r\n");
      out.write("                    width: 30px;\r\n");
      out.write("                }\r\n");
      out.write("                .chat-area form{\r\n");
      out.write("                    padding: 20px;\r\n");
      out.write("                }\r\n");
      out.write("                .chat-area form input{\r\n");
      out.write("                    height: 40px;\r\n");
      out.write("                    width: calc(100% - 48px);\r\n");
      out.write("                }\r\n");
      out.write("                .chat-area form button{\r\n");
      out.write("                    width: 45px;\r\n");
      out.write("                }\r\n");
      out.write("            }");
      out.write(" </style>\r\n");
      out.write("           \r\n");
      out.write("   <script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("      window.addEventListener(\"load\", function (event) {\r\n");
      out.write("    	  let pseudo = \"");
      out.print((email));
      out.write("\";\r\n");
      out.write("          let withClientId = \"");
      out.print((withClientId));
      out.write("\";\r\n");
      out.write("        let ws = new WebSocket(\"ws://localhost:8085/test/chatroom/\" + pseudo);\r\n");
      out.write("        let txtHistory = document.getElementById(\"discussion\");\r\n");
      out.write("        let txtMessage = document.getElementById(\"txtMessage\");\r\n");
      out.write("        let showInputFile = document.getElementById(\"showInputFile\");\r\n");
      out.write("\r\n");
      out.write("        txtMessage.focus();\r\n");
      out.write("\r\n");
      out.write("        ws.addEventListener(\"open\", function (evt) {\r\n");
      out.write("            console.log(\"Connection established\");\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        let btnSend = document.getElementById(\"btnSend\");\r\n");
      out.write("        let fileInput = document.getElementById(\"fileInput\");\r\n");
      out.write("\r\n");
      out.write("        showInputFile.addEventListener(\"click\", function () {\r\n");
      out.write("            if (fileInput.style.display==\"none\"){\r\n");
      out.write("                fileInput.style.display=\"block\";\r\n");
      out.write("                txtMessage.style.display=\"none\";\r\n");
      out.write("            }\r\n");
      out.write("            else {\r\n");
      out.write("                fileInput.style.display=\"none\";\r\n");
      out.write("                txtMessage.style.display=\"block\";\r\n");
      out.write("            }\r\n");
      out.write("            console.log(\"show\");\r\n");
      out.write("        })\r\n");
      out.write("\r\n");
      out.write("        btnSend.addEventListener(\"click\", function (clickEvent) {\r\n");
      out.write("        	\r\n");
      out.write("            let message = {\r\n");
      out.write("                to: withClientId,\r\n");
      out.write("                from : pseudo,\r\n");
      out.write("                message: txtMessage.value\r\n");
      out.write("            };\r\n");
      out.write("\r\n");
      out.write("            if (fileInput.files.length > 0) {\r\n");
      out.write("                let file = fileInput.files[0];\r\n");
      out.write("                let reader = new FileReader();\r\n");
      out.write("                reader.onload = function (loadEvent) {\r\n");
      out.write("                    let fileData = loadEvent.target.result.split(\",\")[1];\r\n");
      out.write("                    message.file = {\r\n");
      out.write("                        name: file.name,\r\n");
      out.write("                        type: file.type,\r\n");
      out.write("                        data: fileData\r\n");
      out.write("                    };\r\n");
      out.write("                    ws.send(JSON.stringify(message));\r\n");
      out.write("                };\r\n");
      out.write("                reader.readAsDataURL(file);\r\n");
      out.write("                txtHistory.innerHTML += '<div class=\"chat outgoing\"> <div class=\"details\"> <p>'+ 'Vous avez envoyé un fichier' + '</p></div> </div>';\r\n");
      out.write("                txtMessage.value = \"\";\r\n");
      out.write("                txtMessage.focus();\r\n");
      out.write("            } else {\r\n");
      out.write("                ws.send(JSON.stringify(message));\r\n");
      out.write("                txtHistory.innerHTML += '<div class=\"chat outgoing\"> <div class=\"details\"> <p>'+ txtMessage.value + '</p></div> </div>';\r\n");
      out.write("                txtMessage.value = \"\";\r\n");
      out.write("                txtMessage.focus();\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        });\r\n");
      out.write("        ws.addEventListener(\"message\", function (evt) {\r\n");
      out.write("            let message_infos = evt.data;\r\n");
      out.write("            let infos_arr = message_infos.split(\",\");\r\n");
      out.write("            if(infos_arr[0] == withClientId){\r\n");
      out.write("                let msgData = infos_arr[2].split(\":\");\r\n");
      out.write("                let typeMsg = msgData[0];\r\n");
      out.write("                if (typeMsg == \"Msg\"){\r\n");
      out.write("                    console.log(\"Receive new message: \" + message_infos);\r\n");
      out.write("                    txtHistory.innerHTML += '<div class=\"chat incoming\"> <div class=\"details\"> <p>'+ msgData[1]+ '</p></div> </div>';\r\n");
      out.write("                }\r\n");
      out.write("                else if (typeMsg == \"File\"){\r\n");
      out.write("                    console.log(\"Receive new message: \" + msgData[1]);\r\n");
      out.write("                    let fileInfos = msgData[1].split(\"|\");\r\n");
      out.write("                    txtHistory.innerHTML += '<div class=\"chat incoming\"> <div class=\"details\"> <a href=\"http://localhost/php/chatApp-ressources//'+fileInfos[0]+'_'+fileInfos[1] + '\"> Telecharger Piéce jointe </a></div> </div>';\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css\"/>\r\n");
      out.write("\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");





int user_id = (int) session.getAttribute("user_id");
Flyweight quoteNotification = new QuoteManager();
List<Flyweight> notifications = quoteNotification.getNotification(user_id);  
int countNotif = notifications.size() ;
String emailNavBar= (String ) session.getAttribute("email") ;

Message message = new Message() ; 
List<Message> msgNotification = message.notification(emailNavBar) ;
int countMsgNotif = msgNotification.size() ;

      out.write("\r\n");
      out.write(" <!--<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\"> -->\r\n");
      out.write("  <nav class=\"navbar navbar-expand-lg\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"index\">Book Quotes</a>\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNav\"\r\n");
      out.write("            aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("            <ul class=\"navbar-nav\">\r\n");
      out.write("                <li class=\"nav-item active\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"sharedQuotes\">Home</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"myQuotes\">My Quotes</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\"\r\n");
      out.write("                        data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                        Community\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"people\">People</a>\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"discussion\">Discussions</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"addQuote\">Add Quotes</a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"profileDropdown\" role=\"button\"\r\n");
      out.write("                        data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                        <i class=\"fas fa-user\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <div class=\"dropdown-menu dropdown-menu-right\" aria-labelledby=\"profileDropdown\">\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"profile\">Profile</a>\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"\">Friends</a>\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"discussion\">Discussions</a>\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"favQuotes\">Favorite Quotes</a>\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"addQuotes\">Add Quote</a>\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"settings\">Account Settings</a>\r\n");
      out.write("                        <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"#\">Sign Out</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                 \r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"notifDropdown\" role=\"button\" data-toggle=\"dropdown\"\r\n");
      out.write("                        aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                        <i class=\"far fa-bell\"></i>\r\n");
      out.write("                        <span class=\"badge badge-warning\">");
      out.print((countNotif));
      out.write("</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  \r\n");
      out.write("                   <div class=\"dropdown-menu dropdown-menu-right\" aria-labelledby=\"notifDropdown\">\r\n");
      out.write("                   \r\n");
      out.write("                    ");

                                       
                                                                              
                                                                              for (Flyweight notifs : notifications ) { 
                                                                                                  	int id_quote = notifs.getId_quote() ;
                                       
      out.write("\r\n");
      out.write("                \r\n");
      out.write("               \r\n");
      out.write("                 <a class=\"dropdown-item\" href=\"sharedQuotes?id_quote=");
      out.print(id_quote);
      out.write("\">New Quote added!</a>\r\n");
      out.write("\r\n");
      out.write("                   \r\n");
      out.write("    ");
} 
      out.write("\r\n");
      out.write("    <div class=\"dropdown-divider\"></div>\r\n");
      out.write("    <a class=\"dropdown-item\" href=\"#\">View All Notifications</a>\r\n");
      out.write("    \r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("</li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                          <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"notifDropdown\" role=\"button\" data-toggle=\"dropdown\"\r\n");
      out.write("                        aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                         <i class=\"far fa-envelope\"></i>\r\n");
      out.write("                        <span class=\"badge badge-warning\">");
      out.print(countMsgNotif );
      out.write("</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  \r\n");
      out.write("                   <div class=\"dropdown-menu dropdown-menu-right\" aria-labelledby=\"notifDropdown\">\r\n");
      out.write("                   \r\n");
      out.write("                    ");
for (Message msgNotif : msgNotification ) { 
                    	String id_from = msgNotif.getFrom() ; 
                    	Message msg = new Message() ;
                    	String  from_name = msg.getName(id_from) ; 
                    	String msgs= msgNotif.getMsg() ;
                     
      out.write("\r\n");
      out.write("                \r\n");
      out.write("               \r\n");
      out.write("                 <a class=\"dropdown-item\" href=\"chat?withClientId=");
      out.print(id_from);
      out.write('"');
      out.write('>');
      out.write(' ');
      out.print(from_name );
      out.write(" : \"");
      out.print(msgs );
      out.write("\" </a>\r\n");
      out.write("\r\n");
      out.write("                   \r\n");
      out.write("    ");
} 
      out.write("\r\n");
      out.write("    <div class=\"dropdown-divider\"></div>\r\n");
      out.write("    <a class=\"dropdown-item\" href=\"#\">View All Messages</a>\r\n");
      out.write("    \r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("</li>\r\n");
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("        setInterval(function() {\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url: \"/notifications\",\r\n");
      out.write("                type: \"GET\",\r\n");
      out.write("                dataType: \"json\",\r\n");
      out.write("                success: function(response) {\r\n");
      out.write("                	 var notifications = JSON.parse(json);\r\n");
      out.write("                     var notificationsHtml = '';\r\n");
      out.write("                     for (var i = 0; i < notifications.length; i++) {\r\n");
      out.write("                         notificationsHtml += '<a class=\"dropdown-item\" href=\"#\">' + notifications[i] + '</a>';\r\n");
      out.write("                     }\r\n");
      out.write("                     document.getElementById('notifications').innerHTML = notificationsHtml;\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }, 5000); // Récupérer les notifications toutes les 5 secondes\r\n");
      out.write("    });\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"wrapper\">\r\n");
      out.write("        <section class=\"chat-area\">\r\n");
      out.write("            <header>\r\n");
      out.write("                <a href=\"people\" class=\"back-icon\"><i class=\"fas fa-arrow-left\"></i></a>\r\n");
      out.write("                <img src=\"peopleProfilePicture?id_user=");
      out.print(idUser );
      out.write("\" alt=\"\">\r\n");
      out.write("                <div class=\"details\">\r\n");
      out.write("                    <span>");
      out.print(withClientName);
      out.write("</span>\r\n");
      out.write("                    <p>status</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </header>\r\n");
      out.write("            <div id=\"discussion\" class=\"chat-box\">\r\n");
      out.write("  ");
 if (my_messages != null ) {
  for (Message msg: my_messages) {
                        String position = "";
                        if (msg.from.equals(email)){
                            position = "outgoing";
                        }
                        else {
                            position = "incoming";
                        }
                        if (msg.type.equals("text")){ 
      out.write("\r\n");
      out.write("                    <div class=\"chat ");
      out.print(position);
      out.write("\"> <div class=\"details\"> <p> ");
      out.print(msg.msg);
      out.write(" </p></div> </div>\r\n");
      out.write("                    ");
 }
                    else { 
      out.write("\r\n");
      out.write("                    <div class=\"chat ");
      out.print(position);
      out.write("\"> <div class=\"details\"> <a href=\"http://localhost/php/chatApp-ressources/");
      out.print(msg.msg);
      out.write("\"> Telecharger Piéce jointe </a></div> </div>\r\n");
      out.write("                    ");
 }
                        }
  
                    } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("              <div class=\"typing-area\">\r\n");
      out.write("                    <input type=\"text\" class=\"incoming_id\" name=\"incoming_id\" value=\"<?php echo $user_id; ?>\" hidden>\r\n");
      out.write("                    <input type=\"text\" name=\"message\" id=\"txtMessage\" class=\"input-field\" placeholder=\"Type a message here...\" autocomplete=\"off\">\r\n");
      out.write("                    <input type=\"file\" id=\"fileInput\">\r\n");
      out.write("                    <button id=\"showInputFile\">File</button>\r\n");
      out.write("                    <button id=\"btnSend\"><i class=\"fab fa-telegram-plane\"></i></button>\r\n");
      out.write("                </div>\r\n");
      out.write("        </section>\r\n");
      out.write("    </div>\r\n");
      out.write("</script>\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		$('.favorite').on('click', function() {\r\n");
      out.write("			$(this).toggleClass('active');\r\n");
      out.write("		});\r\n");
      out.write("		// Get a reference to the edit button\r\n");
      out.write("		// Add a click event listener to the \"Edit\" button\r\n");
      out.write("	</script>\r\n");
      out.write("    </body>\r\n");
      out.write("   \r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
